In [12]:

from torch_geometric.datasets import ZINC
from torch_geometric.loader import DataLoader

from src.utils.utils import TupleIndexer

p = "/Users/arvandkaveh/Projects/kit/graph_hdc/datasets/test/ZINC"
dataset = ZINC(root=p)
loader = DataLoader(dataset, batch_size=2, shuffle=False)
dIter = iter(loader)


In [13]:
d1 = next(dIter)
d2 = next(dIter)
print(d1.x.shape)
print(d2.x.shape)

torch.Size([51, 1])
torch.Size([42, 1])


In [21]:
import torch

# x: [N, D], y: [M, D]
z = torch.cat([d1.x, d2.x], dim=0)  # → [N+M, D]
z.shape

torch.Size([93, 1])

In [26]:
# only works if x.shape == y.shape == [K, D]
z_stacked = torch.stack([z, z], dim=0)  # → [2, K, D]
z_stacked.shape

torch.Size([2, 93, 1])

In [27]:
def mapping_to_cat(t):
    return torch.cat([t, t], dim=0)

In [44]:
big_t = torch.zeros([3, 2, 4, 5])
big_t.shape

torch.Size([3, 2, 4, 5])

In [45]:
a, b, c, d = big_t.shape
print(a, b, c, d)
*A, d = big_t.shape
print(A + [d])

3 2 4 5
[3, 2, 4, 5]


In [47]:
print(big_t.shape)
f = big_t.flatten()
print(f.shape)

g = big_t.unsqueeze(-2)
print(g.shape)
g = big_t.unsqueeze(-1)
print(g.shape)
g = big_t.unsqueeze(0)
print(g.shape)
g = big_t.unsqueeze(1)
print(g.shape)
g = big_t.unsqueeze(2)
print(g.shape)



torch.Size([3, 2, 4, 5])
torch.Size([120])
torch.Size([3, 2, 4, 1, 5])
torch.Size([3, 2, 4, 5, 1])
torch.Size([1, 3, 2, 4, 5])
torch.Size([3, 1, 2, 4, 5])
torch.Size([3, 2, 1, 4, 5])
torch.Size([3, 2, 4, 5])
torch.Size([3, 2, 4, 5])
torch.Size([3, 2, 4, 5])
torch.Size([3, 2, 4, 5])
torch.Size([3, 2, 4, 5])


## Scatter

In [9]:
import torch
from torch_geometric.utils import scatter

# Number of items and feature‐dimension
N, D = 6, 5

# A simple src: rows 0…5 with D features each
src = torch.arange(N * D).view(N, D)
# src =
# tensor([[ 0,  1,  2,  3,  4],
#         [ 5,  6,  7,  8,  9],
#         [10, 11, 12, 13, 14],
#         [15, 16, 17, 18, 19],
#         [20, 21, 22, 23, 24],
#         [25, 26, 27, 28, 29]])

# Assign each of the N rows to a bucket 0,1,2,…
idx = torch.tensor([0, 1, 0, 1, 0, 2], dtype=torch.long)

# We want 4 buckets (0..3), even though idx.max()+1 = 3
dim_size = 4

# Scatter‐sum along dim=0 → out shape [dim_size, D]
out = scatter(src, idx, dim=0, dim_size=dim_size, reduce='sum')

print("src.shape =", src.shape)
print("idx.shape =", idx.shape)
print("out.shape =", out.shape)
print("out =\n", out)

src.shape = torch.Size([6, 5])
idx.shape = torch.Size([6])
out.shape = torch.Size([4, 5])
out =
 tensor([[30, 33, 36, 39, 42],
        [20, 22, 24, 26, 28],
        [25, 26, 27, 28, 29],
        [ 0,  0,  0,  0,  0]])


In [12]:
import torch

a = torch.randn(2, 3)
b = torch.zeros_like(a)


# Indexing

In [3]:
import torch
t = torch.Tensor([
    [0, 10, 20, 30, 40, 50, 60],
    [7, 8, 9, 10, 11, 12, 13]
])
print(t.shape)
indexer = torch.tensor([[0, 1, 2, 0, 1, 2]])
print(indexer.shape)

res = t[0][indexer]
print(res)
print(res.shape)

torch.Size([2, 7])
torch.Size([1, 6])
tensor([[ 0., 10., 20.,  0., 10., 20.]])
torch.Size([1, 6])


In [19]:
import torch


In [20]:
t = torch.Tensor([(0,1), (5, 3)])
print(t.shape)
print(t)

torch.Size([2, 2])
tensor([[0., 1.],
        [5., 3.]])


In [21]:
t = torch.Tensor([[1, 33]])


In [23]:
from src.utils.utils import TupleIndexer

indexer = TupleIndexer([28, 6])

In [25]:
t_ = [int(i.item()) for i in t.squeeze()]
y = torch.tensor(indexer.get_tuples(t_))
